[project]
name = "tfg2025"
version = "0.1.5"
description = "TFG 2025"
requires-python = ">=3.12, <=3.13"
authors = [{ name = "Sergio" }]
dependencies = [
    "pillow",
    "torch",
    "reportlab",
    "scikit-learn",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

